export enum ENetworkEvent {
  EVENT_INITIAL_DATA_REQUESTED = "EVENT_INITIAL_DATA_REQUESTED",
  EVENT_SEND_PLAYER_UPDATE = "EVENT_SEND_PLAYER_UPDATE",
  EVENT_NETWORK_PLAYER_UPDATE = "EVENT_NETWORK_PLAYER_UPDATE",
  EVENT_NETWORK_PLAYER_LEAVE = "EVENT_NETWORK_PLAYER_LEAVE",
  SYNC_LATEST_NETWORK_STATE = "SYNC_LATEST_NETWORK_STATE",
}
export type TNetworkEvent = keyof typeof ENetworkEvent;
